name: Sync branch CI/CD Pipeline

on:
  push:
    branches:
      - staging

permissions:
  contents: write

jobs:
  sync_branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "CI Bot"
          git config user.email "ci@bot.com"

      - name: Sync staging to regional branches
        run: |
          for branch in au nz; do
            git checkout $branch
            git merge --no-ff origin/staging -m "Auto-sync from staging to $branch"
            git checkout -- lib/service/base.dart
            git commit -am "Preserve base.dart" || true
            git push origin $branch
          done
